substitutions:
  clack_select_chl_or_dpsw: Functie mode
  clack_flow_rate: Water debiet
  clack_watermeter_total: Watermeter
  clack_m3_left: Waterontharder m3 over
  clack_l_left: Waterontharder ltr over
  clack_percent_l_left: Waterontharder procent ltr over
  clack_version: Versie
  clack_regeneration_last: Geregenereerd op
  clack_fill_salt: Zout bijvullen
  clack_set_pulse_per_liters: Pulse per liter
  clack_capacity_liters: Capaciteit in liters
  clack_capacity_days: Capaciteit in dagen
  clack_chlorinator_delay: Chlorinator aktief tijd
  clack_leakage_alarm_delay: Vertraging lekkage alarm
  clack_test_motor_run: Testknop motor run
  clack_watermeter_pulse: Watermeter pulse
  clack_regeneration_pulse: Regeneratie pulse
  clack_ip: Waterontharder IP
  clack_wifi_signal_db: WiFi Signaal dB
  clack_wifi_signal_db_percent: WiFi Signaal
  clack_uptime: Uptime
  clack_chlorinator: Chlorinator
  clack_chlorinator_sw: Chlorinator / DP-SW
  clack_dp_sw_init_regen: DP-SW Initialiseer regen
  clack_dp_sw_hold_regen: DP-SW Blokkeer regen
  clack_dp_sw_init_hold: DP-SW Actief
  clack_salt_level_measurement: Zoutniveau meting
  hours: uur
  days: dagen
  clack_yes: ja
  clack_no: nee
  clack_on: Aan
  clack_off: Uit
  clack_power: Vermogen Clack
  clack_voltage: Spanning
  clack_power_esp: Vermogen ESP
  clack_power_chlorinator: Vermogen Chlorinator
  clack_restart: ESP Herstart
  clack_safe_mode: ESP Herstart (Safe Mode)
  clack_regen: clack regen
  clack_brine: Tijdens bezouten
  clack_regeneration_mode: Regeneratie mode
  clack_pre_fill_no_2nd_backwash: Droge zoutbak geen 2e Backwash
  clack_pre_fill_2nd_backwash: Droge zoutbak 2e Backwash
  clack_post_fill_no_2nd_backwash: Natte zoutbak geen 2e Backwash
  clack_post_fill_2nd_backwash: Natte zoutbak 2e Backwash
  clack_time_to_regen: Tijd tot regen.
  clack_time_to_regen_hours: Tijd tot regen uren
  clack_percent_time_left: Waterontharder procent tijd over
  clack_time_to_resinclean: Tijd tot harscleaner
  clack_cycle_runtime: Cyclus runtime
  clack_cycle_total_runtime: Cyclus totale runtime
  clack_resinclean_capacity_days: Harsclean dagen
  clack_reset_but_last_dist: Reset zout bijgevuld
  clack_resinclean_last: Harscleaner op
  clack_saltfill_last: Zout bijgevuld op
  clack_cycle_step: Cyclus stap
  clack_use_tst_but: Testknop verbruik pulse
  clack_resinclean_reset_button: Harsclean reset
  clack_regen_stop_script: Testknop Regen stop
  clack_motor_running: Motor in werking
  clack_water_flowing: Water stroomt
  clack_water_leakage: Lekkage gedetecteerd
  clack_save_total_liters_used: Verbruikt
  clack_save_total_time_used: Werkings tijd
  clack_brine_time_txt: Brine
  clack_backwash_time_txt: Backwash
  clack_backwash2_time_txt: Backwash2
  clack_rinse_time_txt: Rinse
  clack_fill_time_txt: Fill
  clack_service_time_txt: Service
  clack_total_run_time_txt: Run time
  clack_block_regen: Block regen

text_sensor:
  # Expose last regeneration information as sensor
  - platform: template
    name: ${clack_regeneration_last}
    id: clack_regeneration_last
    icon: mdi:clock-start
    update_interval: never
    lambda: |-
      return id(regen_date_last);
    filters:   
      - substitute:
        - "Jan -> jan"
        - "Feb -> feb"
        - "Mar -> mar"
        - "Apr -> apr"
        - "May -> mei"
        - "Jun -> jun"
        - "Jul -> jul"
        - "Aug -> aug"
        - "Sep -> sep"
        - "Okt -> okt"
        - "Nov -> nov"
        - "Dec -> dec"
        - "Mon -> maa"
        - "Tue -> din"
        - "Wed -> woe"
        - "Thu -> don"
        - "Fri -> vri"
        - "Sat -> zat"
        - "Sun -> zon" 

  # Expose last resinclean information as sensor
  - platform: template
    name: ${clack_resinclean_last}
    id: clack_resinclean_last
    icon: mdi:clock-start
    update_interval: never
    lambda: |-
      return id(resinclean_date_last);
    filters:   
      - substitute:
        - "Jan -> jan"
        - "Feb -> feb"
        - "Mar -> mar"
        - "Apr -> apr"
        - "May -> mei"
        - "Jun -> jun"
        - "Jul -> jul"
        - "Aug -> aug"
        - "Sep -> sep"
        - "Okt -> okt"
        - "Nov -> nov"
        - "Dec -> dec"
        - "Mon -> maa"
        - "Tue -> din"
        - "Wed -> woe"
        - "Thu -> don"
        - "Fri -> vri"
        - "Sat -> zat"
        - "Sun -> zon" 

  # Expose last salt fill information as sensor
  - platform: template
    name: ${clack_saltfill_last}
    id: clack_saltfill_last
    icon: mdi:clock-start
    update_interval: never
    lambda: |-
      return id(fill_last);
    filters:   
      - substitute:
        - "Jan -> jan"
        - "Feb -> feb"
        - "Mar -> mar"
        - "Apr -> apr"
        - "May -> mei"
        - "Jun -> jun"
        - "Jul -> jul"
        - "Aug -> aug"
        - "Sep -> sep"
        - "Okt -> okt"
        - "Nov -> nov"
        - "Dec -> dec"
        - "Mon -> maa"
        - "Tue -> din"
        - "Wed -> woe"
        - "Thu -> don"
        - "Fri -> vri"
        - "Sat -> zat"
        - "Sun -> zon" 